OBJS = main.o bookcase.o bookcaseBase.o cabinet.o shelf.o book.o 
SOURCE =  main.cpp bookcase.cpp bookcaseBase.cpp cabinet.cpp shelf.cpp book.cpp
HEADER = bookcase.h bookcaseBase.h cabinet.h shelf.h book.h
PROGRAM = exe
CC = g++ 
CFLAGS = -Wall -W

$(PROGRAM): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROGRAM)

main.o: main.cpp
	$(CC) $(CFLAGS) -c main.cpp

bookcase.o: bookcase.cpp
	$(CC) $(CFLAGS) -c bookcase.cpp

bookcaseBase.o: bookcaseBase.cpp
	$(CC) $(CFLAGS) -c bookcaseBase.cpp

cabinet.o: cabinet.cpp
	$(CC) $(CFLAGS) -c cabinet.cpp

shelf.o: shelf.cpp
	$(CC) $(CFLAGS) -c shelf.cpp

book.o: book.cpp
	$(CC) $(CFLAGS) -c book.cpp

clean:
	rm -f $(OBJS) $(PROGRAM)

run:
	./exe 5 10 11 5

val:
	valgrind --leak-check=full ./exe 5 10 11 5