OBJS = main.o bookcase.o cabinet.o shelf.o 
SOURCE =  main.cpp bookcase.cpp cabinet.cpp shelf.cpp
HEADER = bookcase.h bookcaseBase.h cabinet.h shelf.h book.h
PROGRAM = exe
CC = g++ 
CFLAGS = -Wall

$(PROGRAM): clean $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROGRAM)

main.o: main.cpp
	$(CC) $(CFLAGS) -c main.cpp

bookcase.o: bookcase.cpp
	$(CC) $(CFLAGS) -c bookcase.cpp

cabinet.o: cabinet.cpp
	$(CC) $(CFLAGS) -c cabinet.cpp

shelf.o: shelf.cpp
	$(CC) $(CFLAGS) -c shelf.cpp

clean:
	rm -f $(OBJS) $(PROGRAM)

run:
	./exe 5 10 11 5

val:
	valgrind --leak-check=full ./exe 5 10 11 5